name: Test

on:
  workflow_dispatch:

jobs:
  # Reuse the build job from build.yml
  run:
    name: run
    runs-on: windows-latest
    steps:
      - name: test
        run: |
          $url = "https://github.com/Xcube-Studio/FluentLauncher.PreviewChannel.PackageInstaller/releases/download/test/FluentLauncher.PreviewChannel.PackageInstaller.exe"
          $installerPath = "PackageInstaller-x64.exe"
  
          $ErrorActionPreference = "Stop"
          $ErrorVariable = "DownloadError"
  
          try {
              Invoke-WebRequest -Uri $url -OutFile $installerPath -ErrorAction Stop -ErrorVariable DownloadError
              Write-Output "File downloaded successfully to $installerPath"
          } catch {
              Write-Error "Download failed: $($DownloadError[0])"
              exit 1
          }

          & .\$installerPath query --getBuildCountOfVersion	2.3.2.0
